# labels_to_descriptions.py
LABELS_TO_DESCRIPTIONS = {
    "Abyssinian": "A sleek, short-haired cat with a distinctive coat pattern.",
    "Bengal": "A spotted cat breed with a sleek, muscular body and exotic appearance.",
    "Birman": "A long-haired cat with a creamy coat and deep blue eyes.",
    "Bombay": "A short-haired black cat with a glossy coat and striking golden eyes.",
    "British_Shorthair": "A sturdy cat breed with a dense coat and round face.",
    "Egyptian_Mau": "A cat with a spotted coat and slender body, known for its agility.",
    "Maine_Coon": "A large, long-haired cat with a bushy tail and tufted ears.",
    "Persian": "A long-haired cat with a flat face and calm temperament.",
    "Ragdoll": "A large, long-haired cat with blue eyes and a gentle personality.",
    "Russian_Blue": "A sleek cat with a short, silver-blue coat and green eyes.",
    "Siamese": "A slender cat with a short coat, blue eyes, and pointed color pattern.",
    "Sphynx": "A hairless cat breed known for its wrinkled skin and large ears.",
    
    "American_Bulldog": "A muscular, medium-sized dog with a stocky build and broad head.",
    "American_Pit_Bull_Terrier": "A strong, medium-sized dog with a short coat and a muscular frame.",
    "Basset_Hound": "A short-legged dog with long ears and a sense of smell second only to the Bloodhound.",
    "Beagle": "A small, muscular dog with a white, black, and brown coat.",
    "Boxer": "A medium-sized, short-haired dog with a strong, muscular build and playful nature.",
    "Chihuahua": "A tiny dog with a short or long coat, known for its big personality.",
    "English_Cocker_Spaniel": "A medium-sized dog with a silky coat and friendly personality.",
    "English_Setter": "A medium to large bird dog with a silky, feathered coat and gentle nature.",
    "German_Shorthaired_Pointer": "A versatile hunting dog with a short coat and a lean, muscular build.",
    "Great_Pyrenees": "A large, powerful dog with a thick, white coat, known for guarding livestock.",
    "Havanese": "A small, sturdy dog with a long, silky coat and a friendly temperament.",
    "Japanese_Chin": "A small, toy dog with a silky coat and a distinct, short face.",
    "Keeshond": "A medium-sized dog with a plush, gray-and-black coat and a distinctive mane.",
    "Leonberger": "A giant dog breed with a thick, water-resistant coat and gentle demeanor.",
    "Miniature_Pinscher": "A small, energetic dog with a smooth, shiny coat and confident nature.",
    "Newfoundland": "A large working dog with a heavy coat and webbed feet, known for its strength and loyalty.",
    "Pomeranian": "A tiny dog with a fluffy double coat and a playful, outgoing personality.",
    "Pug": "A small dog with a wrinkled face and curly tail, known for its affectionate nature.",
    "Saint_Bernard": "A giant, friendly dog breed with a thick coat and a reputation as a rescue dog.",
    "Samoyed": "A medium to large dog with a thick, fluffy white coat and a smiling expression.",
    "Scottish_Terrier": "A small, sturdy dog with a wiry coat and a distinctive beard.",
    "Shih_Tzu": "A small, sturdy dog with a long, flowing coat and a friendly temperament.",
    "Staffordshire_Bull_Terrier": "A medium-sized, muscular dog with a short coat and a loyal disposition.",
    "Wheaten_Terrier": "A medium-sized dog with a soft, wavy coat and a friendly personality.",
    "Yorkshire_Terrier": "A small, energetic dog with a long, silky coat and a bold personality."
}
